const questionConstants = {
  LIKE_ANSWER_REQUEST: 'LIKE_ANSWER_REQUEST',
  LIKE_ANSWER_SUCCESS: 'LIKE_ANSWER_SUCCESS',
  LIKE_ANSWER_FAILURE: 'LIKE_ANSWER_FAILURE',
  DISLIKE_ANSWER_REQUEST: 'DISLIKE_ANSWER_REQUEST',
  DISLIKE_ANSWER_SUCCESS: 'DISLIKE_ANSWER_SUCCESS',
  DISLIKE_ANSWER_FAILURE: 'DISLIKE_ANSWER_FAILURE',
  ADD_ANSWER_REQUEST: 'ADD_ANSWER_REQUEST',
  ADD_ANSWER_SUCCESS: 'ADD_ANSWER_SUCCESS',
  ADD_ANSWER_FAILURE: 'ADD_ANSWER_FAILURE',
  DELETE_ANSWER_REQUEST: 'DELETE_ANSWER_REQUEST',
  DELETE_ANSWER_SUCCESS: 'DELETE_ANSWER_SUCCESS',
  DELETE_ANSWER_FAILURE: 'DELETE_ANSWER_FAILURE',
};
export default questionConstants;
