const authConstants = {
  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',
  SIGN_IN_REQUEST: 'USERS_SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'USERS_SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'USERS_SIGN_IN_FAILURE',
  SIGN_OUT: 'USERS_SIGN_OUT',
};

export default authConstants;
