const questionlistContants = {
  QUESTIONLIST_REQUEST: 'GET_QUESTIONLIST_REQUEST',
  QUESTION_SUCCESS: 'GET_QUESTIONLIST_SUCCESS',
  QUESTION_FAILURE: 'GET_QUESTIONLIST_FAILURE',
};

export default questionlistContants;
