const questionConstants = {
  GET_QUESTION_REQUEST: 'GET_QUESTION_REQUEST',
  GET_QUESTION_REQUEST_SUCCESS: 'GET_QUESTION_REQUEST_SUCCESS',
  GET_QUESTION_REQUEST_FAILURE: 'GET_QUESTION_REQUEST_FAILURE',
  LIKE_QUESTION_REQUEST: 'LIKE_QUESTION_REQUEST',
  LIKE_QUESTION_SUCCESS: 'LIKE_QUESTION_SUCCESS',
  LIKE_QUESTION_FAILURE: 'LIKE_QUESTION_FAILURE',
  DISLIKE_QUESTION_REQUEST: 'DISLIKE_QUESTION_REQUEST',
  DISLIKE_QUESTION_SUCCESS: 'DISLIKE_QUESTION_SUCCESS',
  DISLIKE_QUESTION_FAILURE: 'DISLIKE_QUESTION_FAILURE',
  DELETE_QUESTION_REQUEST: 'DELETE_QUESTION_REQUEST',
  DELETE_QUESTION_SUCCESS: 'DELETE_QUESTION_SUCCESS',
  DELETE_QUESTION_FAILURE: 'DELETE_QUESTION_FAILURE',
};
export default questionConstants;
