const userQuestionContants = {
  GET_USER_QUESTIONS_REQUEST: 'GET_USER_QUESTIONS_REQUEST',
  GET_USER_QUESTIONS_SUCCESS: 'GET_USER_QUESTIONS_SUCCESS',
  GET_USER_QUESTIONS_FAILURE: 'GET_USER_QUESTIONS_FAILURE',
};

export default userQuestionContants;
