const router = require('express').Router();
const { addNewQuestion, editQuestion, deleteQuestion, getQuestions, getQuestionById } = require('../controllers/question');
const { questionValidator } = require('../validators/question');
// const { body } = require('express-validator');
const { validate } = require('../middlewares/validateError');
router.get('/questions', validate, getQuestions);
router.post('/questions', questionValidator, validate, addNewQuestion);
router.put('/questions/:question_id', questionValidator, validate, editQuestion);
router.delete('/questions/:question_id', validate, deleteQuestion);
router.get('/questions/:question_id', validate, getQuestionById);
module.exports = router;
